= Manifest


Every application has an application manifest which is part of the app’s properties. This file represents the essential meta-information about the app and contains its capabilities and requirements.

The manifest XML file should not be edited by the programmer directly. To prevent inconsistencies, its content must be edited using the built-in properties editor. This can be accessed by selecting an app in the AppExplorer and choosing "Properties" from the context menu.

The following meta-information is included in the app manifest:

* Name and namespace
* Author
* Version
* Protection
* All components
* Capabilities (Serves)
* Requirements (Uses)


# Manifest contents
[cols="1, 4"]
|===
| *Application name* |
The name of an app corresponds to the name of the project. This name can be changed using the context menu.

| *Meta-information* |
Meta-information such as "Author", "Version", and "Protection". Most of this meta-information can be edited in the "General" tab in the "App Properties" dialog.

| *Components* |
Components referring to the app components used, e.g. "Scripts", "Flows", or "Pages".

| *Capabilities* (Serves) |
If the application publishes functions and/or events which can be used by other components or apps, this must be stated within the "Serves" in the "App Properties" dialog.

| *Requirements* (Uses) |
"Uses" can be declared in the "App Properties" dialog. Here, all functions and events used can be declared. This information is used to verify whether the app(s) fit the target device.
|===


# CROWN data types
The following data types can be used to wire CROWN components for parameters and return values, respectively. Please note that these type definitions are language neutral. See the Scripts section to learn about mapping to Lua.

// comment YS: merged with comments from Mosaic+ page (https://mosaicplus.sick.com/display/wikiAppSpace/Manifest)
[cols="1,6"]
|===
| CROWN Name | Description
| bool |
A basic type representing a boolean value (true or false).
| char |
A basic type representing an Unicode character covering the whole Unicode range (0 - 0x10FFFF).
| int |
A basic type representing a 64-bit signed integer (numerical range from "-2^63" to "+2^63 -1").
| float |
A basic type representing a double-precision floating point according to the standard IEEE 754 (64-bit wide).
| string |
A basic type representing a sequence of Unicode characters. +
The internally used encoding is UTF-8 (a multi-byte encoding covering the whole Unicode range). Note that a single character can occupy either 1, 2, 3, or 4 bytes inside of a string. +
The "alias" attribute can be set to value "function", if the contained string represents a CROWN function, which can be called. This is useful for e.g. callback or register scenarios. Transferred function names should be seen as function references, which are volatile. Thus, the function may not be available any longer after the first use.
| binary |
A basic type representing a sequence of arbitrary bytes/octets. +
The content has no specific encoding.
| enum |
An enumeration of constants. +
Each constant is application-domain specific and is represented by a string value. The strings must not be arbitrary. +
The valid values can be specified directly and locally for the current CROWN and can also be declared globally in the manifest file under the declarations element.
| object |
A complex type representing process data such as Images or Scans. The object may be modified by accessor CROWN functions. Objects can be parameters and return values of other CROWNs. *Objects can therefore be transferred between applications or systems.* +
The alias attribute of the parameter and return value must be set to the full CROWN name to which the object belongs. +
Objects are always shared and not copied automatically. Only references are transferred when passing to and from functions. +
The only exception is the case of event notifications, here the recipients are notified of a distinct deep copy. One of the event receivers will receive the notified object so that the number of copies of the object is minimized. The event notifier must take care that the notified object is then used by one of the event recipients and avoid own further usage. +
Objects are automatically freed if no one holds a reference for it. The app developer has to ensure that distinct apps do not hold a shared reference to the same object and modify asynchronously because of a potential race condition. +
When an "object" data type is serialized and sent via web protocols (REST API, WebSockets), the data type serialized format needs to have a formal specification in the manifest.
|const object |
Same as the complex type "object" but with the difference that a const object is not modifiable. +
*Attempts to modify "const object" are rejected.* +
There is no deep copy done in event notifications for a "const object".
| handle |
A complex type representing a handle to a resource. +
This could be a resource available in the system or a resource created by a user. It belongs to a single CROWN. +
Handles are usually only returned from a create function of a CROWN and are mostly used as the first parameter of accessor functions. +
The alias attribute must be set to the CROWN name to which the handle belongs. +
Handles can also be transferred over functions and events. They are never copied.
| auto |
An auto type representing any of the other types: bool, char, int, float, string, binary, object, handle. The concrete type is decided during runtime by looking at the used types. +
*This means that the implementer of the CROWN function has to handle every possible type.* +
For vector values only the first value is used to detect the type if e.g. calling from a script. The other values will be tried to be converted to the detected type due to performance reasons. If an int-vector contains at least one float value, the whole vector is returned as float value. +
For string values e.g. called from a script, the value is interpreted as binary type. +
It is also allowed to have "const object" types.
| const auto |
Same as the type “auto” but with the difference that the parameters are not modifiable. +
This only affects the object type which will be const.
|===

# Multiplicity
A data type can be declared optional and also as a vector.

A vector is a single argument or return value of the same data type.

To represent a value as a vector, the attribute multiplicity must be set to one of the following quantors. The syntax is similar to regex.

[cols="1, 5"]
|===
| Quantor |	Description
| 1 |
Single value, default.
| ? |
Optional single value, must not be specified as a function parameter. Must also not be returned from functions if specified as a return value.
| + |
Vector value. Could be zero to infinite number of values of the same type.
| * |
Optional vector value.
| [1+] |
Single value or vector. For function which could accept both. Should not be used too much because the user and implementer also have to check for single value and vector.
| [?*] |
Single value or a vector, and could also be nothing (= optional).
|===



