= SICK AppSpace SensorApp Development Guidelines

# General
## Always Using Local
Lua variables are defined as _global_ by default. As this can lead to errors and hard-to-find bugs, it is strongly recommended to declare all variables as _local_ whenever possible.

[source,lua]
----
-- Declare variable as local

local count = 1
local numbers = {1,2,3,4}

-- Declare function as a local variable

local function myFunction()
  -- Function code
end

-- Declare CROWN object as local

local timer1 = Timer.create()
----
## Validating Return Values
Every SensorApp must be programmed in such a way that unexpected return values do not cause the SensorApp to enter into an undetermined state. The SensorApp should expect exceptions as described below and treat them as locally as possible. How exceptions are handled mostly depends on the purpose of the SensorApp. In general, the more defensively an SensorApp is programmed, the more stable and, in particular, the more portable this SensorApp is.

[source, lua]
----
-- Some functions return a handle, for example:
local file = File.open( "private/MyFile.txt" )
local digitalIn = Connector.DigitalIn.create( "DI1" )
----

These handles could be _nil_, for example, when there is no file or hardware resource available with the given name. Some functions return a success value or another value upon which the correct execution can be identified.

In all cases, it is strongly recommended to check if calling such functions returned expected result and handle failures appropriately, or take precautions to prevent the SensorApp from accessing invalid values. In case of exceptions, it may also be sensible to not only treat them but also log them. This is possible by using the _Log_ CROWN.

[source, lua]
----
local portDI1 = Connector.DigitalIn.create( "DI1" )
if ( portDI1 == nil ) then
  Log.severe( "This application requires port DI1!" )
  ...
...
----

## SensorApp Communication Events versus Functions
Events and functions can be served, which makes them a part of the CROWN interface. Therefore, they can be used by different SensorApps or other software. It must be noted that calling a served function blocks the caller until the function returns. Therefore, serving functions should only be used if this behavior is required. In all other cases, it is recommended to use events to communicate.

## Avoiding Sleep Calls
As _Script.sleep_ calls pause the thread, they should not be used unless this behavior is required.

In most cases, it is be better to use events, e.g. _Timer.OnExpired_.

## Multiple SensorApps versus Multiple Scripts
Multiple scripts can be used to define modules and separation of concerns and are loaded into the "main" script with the _require_ statement. As each SensorApp has its own thread, multiple scripts run on the same priority in one SensorApp. If some SensorApp tasks require different priorities, then using multiple SensorApps can be advantageous. Each SensorApp can be assigned different priority in it's Properties. SensorApps should communicate via events to avoid blocking.

## Viewer Calls
A good approach is to use _View.add<Iconic type>_ with declared parent ID and child ID and _View.present_ instead of _View.view_ if there is more than one element to be sent to the user interface at the same time. However, it must be ensured that _View.add<Iconic type>_ calls will never be permitted without a subsequent _View.present_. Otherwise, the image memory will quickly become exhausted. To make it sure this doesn't happen, _View.clear_ can be added after any code that may add something to the viewer.

## Dataflow versus Controlflow
On the one hand, _dataflow_ runs on the priority level of the containing SensorApp and is an easy way to wire functions and events which can be extended with your own functions and events served in a script. This can also contain larger algorithms.

On the other hand, _controlflows_ only allow signal processing. The available function blocks depend on the device and cannot be extended. Other flows and/or scripts can communicate with it by using the events for an input trigger and _Script.notifyEvent_ for an output trigger. The _controlflows_ themselves are running hard real-time and are often even implemented in FPGA on a device. _Controlflows_ are therefore the fastest and most accurate approach for wiring signals virtually.

## Using Descriptions for CROWNs
Creating your own CROWN APIs and serving functions or events in the SensorApp Properties also provides the possibility of adding a description to them. The corresponding fields should be filled in with a proper description. Since served functions and events are part of the CROWN interface and are therefore available in other SensorApps and components, these descriptions will help during development and improve maintainability.

## Registration of Event Handler
Registering to events from a handle should be done with a declared function. It is also possible to register an anonymous function, but this usage should be reserved for the cases when minimal processing is required.

[source, lua]
----

-- Example of registering to declared function

local function handleOnExpired()
  -- Function code
end

Timer.register(handle, "OnExpired", handleOnExpired)

-- Example of registering to an anonymous function

Timer.register(handle, "OnExpired", 
  function()
    -- Function code
  end
)
----

## Engine.OnStarted Event
Using an _Engine.OnStarted_ event in the main script is recommended as a way of starting SensorApp's main loop. This event occurs if the device is fully started, all app components (including flows) are loaded, and the global scope of each script has finished. This ensures that all functions and events within the scope, as well as served functions and events from other SensorApps, are ready and known to the engine before their call.

## Write Operations
Since the physical memory of the devices can have limited lifetime, to prevent premature failure, fast repetitive write operations should not be performed on the device flash (public/private folder). If the information stored should be preserved between power cycles, externally mounted memory, such as SD-cards, is recommended. On the other hand, when the stored data is only used during the SensorApp's execution, a RAM virtual folder can be used instead. The RAM virtual folder shares memory with the process memory of the device and thus it is not recommended to use it for storage of large quantity of data.

## Data Cleanup
SensorApps may run on an embedded system which might have quite limited resources and where file space is not endless. All files, variables and objects which are created at runtime by the SensorApp should also be cleaned up by the SensorApp, if possible. This is particularly essential if values are stored in a global scope and therefore the memory they use is never automatically made available by garbage collection.

## File Names
The system of SICK AppSpace programmable devices usually is based on a Linux kernel. The characteristics of such operating systems make it so the file and folder operations take in count the case of their names. Therefore, it is important to refer in lua scripts to files and folder with the consideration of letter case.

# Deployment
After the development phase, SensorApps can be deployed in a package for further distribution or for installation on AppSpace devices with AppManager.

## Prerequisites
When deploying a package, any SensorApp in the current Workspace can be deployed. Therefore, it is important to select only those that are necessary for the final package. All irrelevant SensorApps should be removed or must at least be deselected during package step. It is recommended to also select each SensorApps manifest as active. +
The Uses section in the Properties of each SensorApp should be up to date. This will ensure that the SensorApps are suitable for the device when they are installed. +
The version and author information in the Properties of each SensorApp should be checked and updated if necessary.

## SensorApp Protection
SensorApps can optionally be read-only or copy-protected. To ensure that this protection is enabled, the corresponding property must be set in each SensorApp. It must be noted that protection is only activated after the package on the device has been installed.

## Release Notes
The deployment dialog offers the possibility to attach release notes. It is strongly recommended to use this feature. The release notes can be read within AppManager before Installation.

# Naming Conventions
When developing SensorApps, the following naming conventions should be applied. All naming should follow the conventions of American English.

## SensorApps
The SensorApps should be named using *PascalCase*. 

## SensorApp components
### Scripts
All scripts should be named using *PascalCase*.
The main script should follow the same convention, copying the name of the SensorApp. Alternatively it can be _main.lua_.

### Resources
There are no special naming conventions for the resources.

### Pages
In the _pages_ component there are only the following options for re-naming files, or folders. Any other modifications may cause the UI building process to fail.

#### i18n files
Names of such files should always be _<ISO 639-1 code for the language>.json_.

#### Individual pages
Individual pages are to be stored in separate folders inside _pages_ subdir of the _pages_ component. Individual page should always contain one HTML file and optionally a style sheet for this individual page.
There are no special naming conventions for the HTML pages.
The style sheet file for the individual page needs to be always named _style.css_.

### Flows
The flows should be named using *PascalCase*.

### Parameters
Parameter files can be named using either *camelCase* or *PascalCase*.

## Lua files

### Local variables
All local variables should be named using *camelCase*.

### Global Variables
All global variables should be named using *PascalCase*.

### Event serving
All event serve calls should be placed on the top of the lua file.
Avoid using the same local event names in the same SensorApp.
Event names used locally in the script should be in *PascalCase* and generally should be the similar to ones declared in the manifest.

[source, lua]
----
-- The event is served under the name MyEvent in the manifest and in the script.
Script.serveEvent("MyApp1.MyEvent", "MyEvent")

Script.notifyEvent("MyEvent")
----

### Function serving
Function serve calls can either be placed directly after the function declaration or in the bottom the the lua file.
The function name in the manifest should be the same as in the script.

[source,lua]
----
-- First the function is declared

--- Performs some operation
---@return bool
local myFunction ()
  -- Function code

  return true
end
-- Secondly, it is served
Script.serveFunction("MyApp1.myFunction", myFunction)
----

## CROWN
### Sub-CROWN names
All sub-CRONWs should be named using *PascalCase*.

### Events
Events should be named using *PascalCase*.
If the event will be notified as a result of some process completing, it should be named starting with _On_ and refer to the process name or general purpose. For example, we have a function named _processImages_ that that applies a series of analytical functions to an image. The event that provides the results of this processing can be _OnProcessImagesFinished_ or similar.

### Functions
The CROWN functions should be named the same as the function in script they serve, usually using *camelCase*.

### Enums
Enums names should all be in *ALL_CAPS*.

### Properties
Names of the properties should be in *camelCase* because basically they represent a variable.

# Other considerations

## Abbreviations
Abbreviations in names should all be written in uppercase, e.g. "ID" should be written in uppercase:

[source, lua]
----
local digitalIO = DigitalIO.create()
local clientTCP = TCPClient.create()
----

## Annotations and comments
Annotating the code using the emmyLua convention helps the language server to provide the code completion hints and provides an opportunity to write documentation. At least, functions that have inputs and outputs should always be annotated. Providing annotations in other cases is also useful. To learn more about how to construct annotations, refer to https://github.com/SICKAG/SICK-AppSpace-SDK-Docs/blob/master/Programming-SensorApps-LUA-Annotations/Programming-SensorApps-LUA-Annotations.adoc[annotation guide].

Comments can be written using lua standard comment functionality - double dashes for one line or in-line comments and --[[ ]]-- structure for block comments.

## Indentation
Two spaces must be used as an indent. The editor is configured to enter two spaces by default when the tab button is pressed.

## Line Length
A single line of code should not exceed 80 characters and must not exceed more than 120 characters.

## Spreading code
For the ease of reading, it is best to put line breaks between to separate each operation.

Don't:

[source, lua]
----
for i = 1, 10 do doSomething() end
----

Do:

[source, lua]
----
for i=1, 10 do
  doSomething()
end
----
