= Resources

# Overview
Resources are any kind of file(s) which is/are needed by the application. The file type is not defined by SICK AppSpace but by the application itself. For instance, a resource file could be a HALCON script, which is a subpart of the application itself. Furthermore, test data or reference data such as images can be added as resources to the application. This component is not limited to any file type nor is it limited to a specific purpose. However, it should be kept in mind that space on the device is limited and therefore only required files should be part of the resources. Resources are private and cannot be accessed by other apps which may exist on the device. Files in resources are read-only and as they belong directly to the application, they are not available if the app is not running. Resource files can be added to the component "resources" of the app using the "Working direcory" in SICK AppStudio.


# Accessing resources
As resources are simply files, they can be accessed via the File API. For instance, in Lua the resource file MyRes.txt can be accessed with the following code:

[source, lua]
--
resourceFile = File.open("resources/MyRes.txt")
--



